### ISSUE TITLE
Usage of r2dbc-pool with Komapper and far jar

### ISSUE THREAD

**Issue by raharrison** [komapper/komapper#1060]
### Describe the bug

When trying to use the `r2dbc-pool` (https://github.com/r2dbc/r2dbc-pool) library for connection pooling with `komapper-r2dbc` and Postgres, the application fails to load both drivers (pool/postgresql) at runtime when deployed as a fat/uber jar file.

This is strangely only an issue when running from the jar file, not when running through the IDE - where both are correctly picked up. I'm unsure if this is an issue with Komapper, Gradle or R2DBC, but others online have pointed out that Gradle `implementation` vs `runtimeOnly` might be an issue and this dependency is pulled transitively from Komapper.

### Expected behavior

The `R2dbcDatabase` should use successfully use connection pooling with Postgres through the `r2dbc-pool` library

### Actual behavior

The `pool` driver to load at runtime. With various Gradle configurations I can get either `pool` or `postgresql` drivers to load, but never both. This causes the connection factory to fail with the exceptions below:

```
Exception in thread "main" java.lang.IllegalStateException: Unable to create a ConnectionFactory for 'ConnectionFactoryOptions{options={driver=pool, password=REDACTED, protocol=postgresql, database=aridb, host=localhost, user=ariuser}}'. Available drivers: [ postgresql ]
        at io.r2dbc.spi.ConnectionFactories.get(ConnectionFactories.java:143)
        at org.komapper.r2dbc.R2dbcDatabaseKt.R2dbcDatabase$default(R2dbcDatabase.kt:194)
        at MainKt.connect(Main.kt:21)
        at MainKt.main(Main.kt:8)
        at MainKt.main(Main.kt)
```
or depending on Gradle config could also be:

```
Exception in thread "main" java.lang.IllegalArgumentException: Could not find delegating driver [postgresql]
        at io.r2dbc.pool.PoolingConnectionFactoryProvider.buildConfiguration(PoolingConnectionFactoryProvider.java:191)
        at io.r2dbc.pool.PoolingConnectionFactoryProvider.create(PoolingConnectionFactoryProvider.java:167)
        at io.r2dbc.pool.PoolingConnectionFactoryProvider.create(PoolingConnectionFactoryProvider.java:43)
        at io.r2dbc.spi.ConnectionFactories.find(ConnectionFactories.java:110)
        at io.r2dbc.spi.ConnectionFactories.get(ConnectionFactories.java:140)
        at org.komapper.r2dbc.R2dbcDatabaseKt.R2dbcDatabase(R2dbcDatabase.kt:201)
```

### Steps to reproduce the problem

I have created a minimal reproducible example project at: https://github.com/raharrison/r2dbc-test which is just a single file trying to create an `R2dbcDatabase` with pooling.

- Adds in `komapper` and` r2dbc-pool`  dependencies with Gradle as standard
- Tries to create a connection with `R2dbcDatabase`. As per pool docs uses driver property as `pool` and protocol as `postgresql`
- Also prints out the loaded drivers for debugging using same logic as internal to `io.r2dbc.spi.ConnectionFactoryProvider`
- When ran in an IDE the app works fine and loads both drivers
- Create fat jar through `gradlew shadowJar` and run through simple ` java -jar .\r2dbc-test-all.jar` results in the errors above

I've tried going the the differences in jar files and can't see any obvious changes that would prevent one driver or the other from loading. Do you know of anyone else who was able to get r2dbc-pool working with komapper?

### Versions

- Komapper:1.12.1
- Kotlin:1.9.0
- JVM:20
- JDBC Driver or R2DBC Driver:R2DBC
- Database:Postgres
- OS:Windows/Linux

**Comment by momosetkn** [comment]
Maybe this Issues is related to `ServiceLoader#load`.

I met this issue too. This is how I solved it.
Add below code to `build.gradle.kts`.

```kotlin

plugins {
    id("com.github.johnrengelman.shadow") version "8.1.1"
}
tasks {
    withType<com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar>() {
        mergeServiceFiles()
    }
}
```

For more information by My blog...
https://zenn.dev/momosetkn/articles/b92fd0159bd9f4#%E8%A4%87%E6%95%B0%E3%81%AEdialect%E3%82%92%E4%BD%BF%E3%81%86%E5%A0%B4%E5%90%88%E3%81%AE%E6%B3%A8%E6%84%8F%E7%82%B9

**Comment by nakamura-to** [comment]
@momosetkn, thank you for sharing.
I have confirmed that the problem can be solved that way.

Documentation is available here:
https://imperceptiblethoughts.com/shadow/configuration/merging/#merging-service-descriptor-files

**Comment by raharrison** [comment]
Ah perfect, thank you both for the pointer!
