### ISSUE TITLE
 When using Spring Boot and MySQL, an error occurs during transaction processing

### ISSUE THREAD

**Issue by imori425** [komapper/komapper#1235]
### Describe the bug
When implementing transaction processing using Komapper with Spring Boot and MySQL, an error occurred with java.lang.IllegalStateException: The connection is closed. This issue arises in a project that was changed from H2 to MySQL, referring to example/spring-boot-r2dbc that uses R2DBC in Spring Boot.

The following error log was output:

```
java.lang.IllegalStateException: The connection is closed
	at _COROUTINE._BOUNDARY._(CoroutineDebugging.kt:46) ~[kotlinx-coroutines-core-jvm-1.7.3.jar:na]
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	*__checkpoint ⇢ Handler org.komapper.example.DeclarativeTxController#add(String, Continuation) [DispatcherHandler]
	*__checkpoint ⇢ HTTP GET "/?text=Hi!" [ExceptionHandlingWebHandler]
Original Stack Trace:
		at _COROUTINE._BOUNDARY._(CoroutineDebugging.kt:46) ~[kotlinx-coroutines-core-jvm-1.7.3.jar:na]
		at kotlin.reflect.full.KCallables.callSuspendBy(KCallables.kt:74) ~[kotlin-reflect-1.9.23.jar:1.9.23-release-779]
Caused by: java.lang.IllegalStateException: The connection is closed
	at io.r2dbc.pool.PooledConnection.assertNotClosed(PooledConnection.java:208) ~[r2dbc-pool-1.0.1.RELEASE.jar:1.0.1.RELEASE]
	at io.r2dbc.pool.PooledConnection.isAutoCommit(PooledConnection.java:140) ~[r2dbc-pool-1.0.1.RELEASE.jar:1.0.1.RELEASE]
	at org.springframework.r2dbc.connection.R2dbcTransactionManager.lambda$doCleanupAfterCompletion$14(R2dbcTransactionManager.java:361) ~[spring-r2dbc-6.1.5.jar:6.1.5]
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:45) ~[reactor-core-3.6.4.jar:3.6.4]
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:53) ~[reactor-core-3.6.4.jar:3.6.4]
	at reactor.core.publisher.Mono.subscribe(Mono.java:4568) ~[reactor-core-3.6.4.jar:3.6.4]
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:265) ~[reactor-core-3.6.4.jar:3.6.4]
	at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:51) ~[reactor-core-3.6.4.jar:3.6.4]
	at reactor.core.publisher.Mono.subscribe(Mono.java:4568) ~[reactor-core-3.6.4.jar:3.6.4]
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:103) ~[reactor-core-3.6.4.jar:3.6.4]
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onError(MonoIgnoreThen.java:280) ~[reactor-core-3.6.4.jar:3.6.4]
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:106) ~[reactor-core-3.6.4.jar:3.6.4]
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onError(MonoIgnoreThen.java:280) ~[reactor-core-3.6.4.jar:3.6.4]
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:232) ~[reactor-core-3.6.4.jar:3.6.4]
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onComplete(MonoIgnoreThen.java:204) ~[reactor-core-3.6.4.jar:3.6.4]
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onComplete(MonoIgnoreThen.java:210) ~[reactor-core-3.6.4.jar:3.6.4]
	at reactor.core.publisher.Operators.complete(Operators.java:137) ~[reactor-core-3.6.4.jar:3.6.4]
	at reactor.core.publisher.MonoEmpty.subscribe(MonoEmpty.java:46) ~[reactor-core-3.6.4.jar:3.6.4]
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:53) ~[reactor-core-3.6.4.jar:3.6.4]
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:241) ~[reactor-core-3.6.4.jar:3.6.4]
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onComplete(MonoIgnoreThen.java:204) ~[reactor-core-3.6.4.jar:3.6.4]
	at reactor.core.publisher.MonoIgnoreElements$IgnoreElementsSubscriber.onComplete(MonoIgnoreElements.java:89) ~[reactor-core-3.6.4.jar:3.6.4]
	at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onComplete(FluxContextWrite.java:126) ~[reactor-core-3.6.4.jar:3.6.4]
	at reactor.core.publisher.FluxConcatMapNoPrefetch$FluxConcatMapNoPrefetchSubscriber.onComplete(FluxConcatMapNoPrefetch.java:241) ~[reactor-core-3.6.4.jar:3.6.4]
	at reactor.core.publisher.Operators.complete(Operators.java:137) ~[reactor-core-3.6.4.jar:3.6.4]
	at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:144) ~[reactor-core-3.6.4.jar:3.6.4]
	at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:83) ~[reactor-core-3.6.4.jar:3.6.4]
	at reactor.core.publisher.Mono.subscribe(Mono.java:4568) ~[reactor-core-3.6.4.jar:3.6.4]
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:265) ~[reactor-core-3.6.4.jar:3.6.4]
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onComplete(MonoIgnoreThen.java:204) ~[reactor-core-3.6.4.jar:3.6.4]
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onComplete(Operators.java:2231) ~[reactor-core-3.6.4.jar:3.6.4]
	at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onComplete(Operators.java:2231) ~[reactor-core-3.6.4.jar:3.6.4]
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:260) ~[reactor-core-3.6.4.jar:3.6.4]
	at reactor.core.publisher.MonoIgnoreElements$IgnoreElementsSubscriber.onComplete(MonoIgnoreElements.java:89) ~[reactor-core-3.6.4.jar:3.6.4]
	at reactor.core.publisher.MonoCompletionStage$MonoCompletionStageSubscription.apply(MonoCompletionStage.java:122) ~[reactor-core-3.6.4.jar:3.6.4]
	at reactor.core.publisher.MonoCompletionStage$MonoCompletionStageSubscription.apply(MonoCompletionStage.java:67) ~[reactor-core-3.6.4.jar:3.6.4]
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[na:na]
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147) ~[na:na]
	at com.github.jasync.sql.db.util.FutureUtilsKt.success(FutureUtils.kt:16) ~[jasync-pool-2.2.4.jar:na]
	at com.github.jasync.sql.db.mysql.MySQLConnection$succeedQueryPromise$1.invoke(MySQLConnection.kt:424) ~[jasync-mysql-2.2.4.jar:na]
	at com.github.jasync.sql.db.mysql.MySQLConnection$succeedQueryPromise$1.invoke(MySQLConnection.kt:423) ~[jasync-mysql-2.2.4.jar:na]
	at com.github.jasync.sql.db.mysql.MySQLConnection.succeedQueryPromise$lambda$14(MySQLConnection.kt:423) ~[jasync-mysql-2.2.4.jar:na]
	at java.base/java.util.Optional.ifPresent(Optional.java:178) ~[na:na]
	at com.github.jasync.sql.db.mysql.MySQLConnection.succeedQueryPromise(MySQLConnection.kt:423) ~[jasync-mysql-2.2.4.jar:na]
	at com.github.jasync.sql.db.mysql.MySQLConnection.onOk(MySQLConnection.kt:240) ~[jasync-mysql-2.2.4.jar:na]
	at com.github.jasync.sql.db.mysql.codec.MySQLConnectionHandler.channelRead0(MySQLConnectionHandler.kt:124) ~[jasync-mysql-2.2.4.jar:na]
```

### Expected behavior

It is expected that the transaction processing completes successfully without the java.lang.IllegalStateException: The connection is closed error, and changes to the database are committed.

### Steps to reproduce the problem

The error can be reproduced by using the @Transactional annotation or the database.withTransaction method. Commenting these out completes the process without any errors.

The behavior was confirmed with the following repository:
https://github.com/imori425/springboot-komapper-r2dbc-mysql

You can confirm it by launching the MySQL container from container/docker-compose.yml and running ApplicationTest.

### Versions

- Komapper: 1.17.0
- Kotlin: 1.9.23
- SpringBoot: 3.2.4
- JVM: 17
- R2DBC Driver: jasync-mysql-2.2.4
- Database: MySQL 8.0.3

**Comment by nakamura-to** [comment]
フィードバックありがとうございます。
提供いただいた再現プロジェクトではSpring Frameworkのv6.1.5が使用されていました。

KomapperはSpring Framework連携モジュールはSpring Frameworkのv5.3系で動作確認をしていますが、Spring FrameworkのR2dbcTransactionManagerの修正差分が今回のエラーの原因だと思われます。

以下のワークアラウンドのいずれかをお試しください。

## ワークアラウンド
### ワークアラウンド1
Spring Frameworkのv5.3系を利用する

### ワークアラウンド2
以下のようにしてKomapperのSpring Framework連携モジュール内のコンポーネントを置き換える

1. build.gradle.kts に依存を追加する
```kotlin
implementation("org.komapper:komapper-spring-r2dbc")
```

2. ConnectionをKomapper側で閉じないようにするR2dbcSessionの実装クラスを作成する
```kotlin
class MySpringR2dbcTransactionSession(
    transactionManager: ReactiveTransactionManager,
    connectionFactory: ConnectionFactory,
) : R2dbcSession by SpringR2dbcTransactionSession(transactionManager, connectionFactory) {
    override suspend fun releaseConnection(connection: Connection) {
        // do nothing
    }

    override suspend fun <R> useConnection(block: suspend (Connection) -> R): R {
        return super.useConnection(block)
    }
}
```

3. 上述のクラスをSpring Frameworkに認識させる
```kotlin
@Configuration
class MyConfiguration {
    @Bean
    open fun session(
        transactionManager: ReactiveTransactionManager,
        connectionFactory: ConnectionFactory,
    ): R2dbcSession {
        return MySpringR2dbcTransactionSession(transactionManager, connectionFactory)
    }
}
```

## ご相談
登録したissueですが、機械翻訳などでも構いませんので英語にしてもらうことは可能でしょうか？
英語に翻訳したい理由としましては、より多くの方に情報共有をしたいためです。
私に編集権限があるようなので私の方で対応しても構いません。
私の上述のワークアラウンドの説明も最終的には英語にしたいと思います

**Comment by imori425** [comment]
@nakamura-to 
Thank you for your response. I overlooked the version change for the Spring Framework. My apologies. Following workaround 2, I replaced the proposed components and confirmed that it is now working properly without any issues.

As for the issue content, I used machine translation to translate it into English. If there are any problems with the content, please feel free to edit it.

**Comment by nakamura-to** [comment]
This issue will be resolved in versions above Komapper v1.7.0

**Comment by nakamura-to** [comment]
@imori425  This issue has been resolved in Komapper v1.17.1. Please give it a try.
