### ISSUE TITLE
r2dbc-mssql does not respond until timeout

### ISSUE THREAD

**Issue by nakamura-to** [komapper/komapper#427]
### Describe the bug

r2dbc-mssql sometimes does not  respond until timeout in CI.

There is probably a bug in one of the following places:

- komapper-r2dbc
- kotlinx-coroutines-core
- kotlinx-coroutines-reactive
- r2dbc-mssql

### Expected behavior

It works without timeout exception.

### Actual behavior

The following exception is thrown:

<details>
<summary>stacktrace</summary>

```
kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 30000 ms
	at ???(Coroutine boundary.?(?)
	at kotlinx.coroutines.channels.AbstractChannel.receiveCatching-JP2dKIU(AbstractChannel.kt:633)
	at kotlinx.coroutines.reactive.ReactiveSubscriber.takeNextOrNull(ReactiveFlow.kt:129)
	at kotlinx.coroutines.reactive.PublisherAsFlow.collectImpl(ReactiveFlow.kt:98)
	at kotlinx.coroutines.flow.FlowKt__MergeKt$flatMapConcat$$inlined$map$1$2.emit(Merge.kt:136)
	at kotlinx.coroutines.reactive.PublisherAsFlow.collectImpl(ReactiveFlow.kt:100)
	at kotlinx.coroutines.flow.FlowKt__EmittersKt$onStart$$inlined$unsafeFlow$1.collect(Emitters.kt:120)
	at kotlinx.coroutines.flow.FlowKt__ErrorsKt.catchImpl(Errors.kt:227)
	at kotlinx.coroutines.flow.FlowKt__ErrorsKt$catch$$inlined$unsafeFlow$1.collect(Errors.kt:113)
	at org.komapper.r2dbc.dsl.runner.R2dbcScriptExecuteRunner.run(R2dbcScriptExecuteRunner.kt:20)
	at integration.r2dbc.Env$beforeTestExecution$1$1.invokeSuspend(Env.kt:52)
	at org.komapper.tx.r2dbc.R2dbcTransactionScopeImpl$executeInNewTransaction$2.invokeSuspend(R2dbcTransactionScope.kt:60)
	at org.komapper.tx.r2dbc.TransactionManagerImpl.begin(R2dbcTransactionManager.kt:102)
	at integration.r2dbc.Env$beforeTestExecution$1.invokeSuspend(Env.kt:51)
	at integration.r2dbc.UtilityKt$runBlockingWithTimeout$1.invokeSuspend(utility.kt:21)
Caused by: kotlinx.coroutines.TimeoutCancellationException: Timed out waiting for 30000 ms
	at app//kotlinx.coroutines.TimeoutKt.TimeoutCancellationException(Timeout.kt:186)
	at app//kotlinx.coroutines.TimeoutCoroutine.run(Timeout.kt:156)
	at app//kotlinx.coroutines.EventLoopImplBase$DelayedRunnableTask.run(EventLoop.common.kt:497)
	at app//kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:274)
	at app//kotlinx.coroutines.DefaultExecutor.run(DefaultExecutor.kt:69)
	at java.base@11.0.11/java.lang.Thread.run(Thread.java:829)
```

</details>

### Steps to reproduce the problem

- Run the [Build](https://github.com/komapper/komapper/blob/v0.28.0/.github/workflows/build.yml) workflow. Sometimes the unstable-test-r2dbc job fails.

### Versions

- Komapper: 0.28.0
- Kotlin: 1.5.31
- JVM: temurin 11
- JDBC Driver or R2DBC Driver: r2dbc-mssql 0.9.0.RELEASE
- Database: SQL Server 2019-CU12
- OS: Ubuntu 20.04.3

**Comment by nakamura-to** [comment]
The resolution of #425 may be relevant to the resolution of this issue.
