### ISSUE TITLE
komapperGenerator sometimes creates uncompilable entities

### ISSUE THREAD

**Issue by donard-commedagh** [komapper/komapper#608]
### Describe the bug

The auto-generated `entities.kt` and `entityDefinitions.kt` will not compile when certain table names exist in the database. In my case, the database has a table named `Class`.

I have not tested, but I assume that tables named after other Java/Kotlin keywords may also have problems.

Note: I am working against an established database and the schema cannot be changed.

### Expected behavior

The entity generation code should always be able to generate entities that compile.

### Actual behavior

When compiling the code the following error is produced:
```
16:38:42: Executing ':classes'...

Starting Gradle Daemon...
Gradle Daemon started in 3 s 945 ms
> Task :wrapper

BUILD SUCCESSFUL in 32s
1 actionable task: 1 executed

> Task :kspKotlin FAILED
e: [ksp] java.lang.NullPointerException
	at com.google.devtools.ksp.symbol.impl.kotlin.KSDeclarationImpl$simpleName$2.invoke(KSDeclarationImpl.kt:38)
	at com.google.devtools.ksp.symbol.impl.kotlin.KSDeclarationImpl$simpleName$2.invoke(KSDeclarationImpl.kt:37)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at com.google.devtools.ksp.symbol.impl.kotlin.KSDeclarationImpl.getSimpleName(KSDeclarationImpl.kt:37)
	at com.google.devtools.ksp.symbolCollector.visitDeclaration(Incremental.kt:151)
	at com.google.devtools.ksp.symbolCollector.visitDeclaration(Incremental.kt:144)
	at com.google.devtools.ksp.visitor.KSDefaultVisitor.visitPropertyDeclaration(KSDefaultVisitor.kt:53)
	at com.google.devtools.ksp.symbol.impl.kotlin.KSPropertyDeclarationImpl.accept(KSPropertyDeclarationImpl.kt:115)
	at com.google.devtools.ksp.symbolCollector.visitDeclarationContainer(Incremental.kt:164)
	at com.google.devtools.ksp.symbolCollector.visitDeclarationContainer(Incremental.kt:144)
	at com.google.devtools.ksp.visitor.KSDefaultVisitor.visitClassDeclaration(KSDefaultVisitor.kt:80)
	at com.google.devtools.ksp.symbol.impl.kotlin.KSClassDeclarationImpl.accept(KSClassDeclarationImpl.kt:136)
	at com.google.devtools.ksp.symbolCollector.visitDeclarationContainer(Incremental.kt:164)
	at com.google.devtools.ksp.symbolCollector.visitDeclarationContainer(Incremental.kt:144)
	at com.google.devtools.ksp.visitor.KSDefaultVisitor.visitClassDeclaration(KSDefaultVisitor.kt:80)
	at com.google.devtools.ksp.symbol.impl.kotlin.KSClassDeclarationImpl.accept(KSClassDeclarationImpl.kt:136)
	at com.google.devtools.ksp.symbolCollector.visitDeclarationContainer(Incremental.kt:164)
	at com.google.devtools.ksp.symbolCollector.visitDeclarationContainer(Incremental.kt:144)
	at com.google.devtools.ksp.visitor.KSDefaultVisitor.visitFile(KSDefaultVisitor.kt:32)
	at com.google.devtools.ksp.symbol.impl.kotlin.KSFileImpl.accept(KSFileImpl.kt:61)
	at com.google.devtools.ksp.IncrementalContext.collectDefinedSymbols(Incremental.kt:228)
	at com.google.devtools.ksp.IncrementalContext.registerGeneratedFiles(Incremental.kt:534)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension$doAnalysis$1.invoke(KotlinSymbolProcessingExtension.kt:166)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension$doAnalysis$1.invoke(KotlinSymbolProcessingExtension.kt:147)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension.handleException(KotlinSymbolProcessingExtension.kt:313)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension.doAnalysis(KotlinSymbolProcessingExtension.kt:147)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration(TopDownAnalyzerFacadeForJVM.kt:123)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration$default(TopDownAnalyzerFacadeForJVM.kt:99)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:301)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:55)
	at org.jetbrains.kotlin.cli.common.messages.AnalyzerWithCompilerReport.analyzeAndReport(AnalyzerWithCompilerReport.kt:113)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.analyze(KotlinToJVMBytecodeCompiler.kt:292)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.repeatAnalysisIfNeeded(KotlinToJVMBytecodeCompiler.kt:236)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:102)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli$default(KotlinToJVMBytecodeCompiler.kt:60)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:172)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:54)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:91)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:43)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:93)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1623)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:359)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:691)
	at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:587)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:828)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:705)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:704)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)

e: Error occurred in KSP, check log for detail
e: C:\Users\PC\Projects\Kotlin\KomapperClassTest\build\generated\ksp\main\kotlin\org\example\sqlserver\_ClassDef.kt: (51, 12): Expecting property name or receiver type
e: C:\Users\PC\Projects\Kotlin\KomapperClassTest\build\generated\ksp\main\kotlin\org\example\sqlserver\_ClassDef.kt: (51, 12): Property getter or setter expected
e: C:\Users\PC\Projects\Kotlin\KomapperClassTest\build\generated\ksp\main\kotlin\org\example\sqlserver\_ClassDef.kt: (51, 19): Name expected
e: C:\Users\PC\Projects\Kotlin\KomapperClassTest\build\generated\ksp\main\kotlin\org\example\sqlserver\_ClassDef.kt: (51, 21): Expecting member declaration
e: C:\Users\PC\Projects\Kotlin\KomapperClassTest\build\generated\ksp\main\kotlin\org\example\sqlserver\_ClassDef.kt: (51, 30): Expecting member declaration
e: C:\Users\PC\Projects\Kotlin\KomapperClassTest\build\generated\ksp\main\kotlin\org\example\sqlserver\_ClassDef.kt: (51, 31): Expecting member declaration
e: C:\Users\PC\Projects\Kotlin\KomapperClassTest\build\generated\ksp\main\kotlin\org\example\sqlserver\_ClassDef.kt: (55, 32): Expecting property name
e: C:\Users\PC\Projects\Kotlin\KomapperClassTest\build\generated\ksp\main\kotlin\org\example\sqlserver\_ClassDef.kt: (55, 32): Property getter or setter expected
e: C:\Users\PC\Projects\Kotlin\KomapperClassTest\build\generated\ksp\main\kotlin\org\example\sqlserver\_ClassDef.kt: (55, 44): Expecting a top level declaration
e: C:\Users\PC\Projects\Kotlin\KomapperClassTest\build\generated\ksp\main\kotlin\org\example\sqlserver\_ClassDef.kt: (55, 46): Expecting a top level declaration
e: C:\Users\PC\Projects\Kotlin\KomapperClassTest\build\generated\ksp\main\kotlin\org\example\sqlserver\_ClassDef.kt: (55, 55): Expecting a top level declaration
e: C:\Users\PC\Projects\Kotlin\KomapperClassTest\build\generated\ksp\main\kotlin\org\example\sqlserver\_ClassDef.kt: (55, 61): Name expected

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':kspKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 11s
1 actionable task: 1 executed
16:39:26: Execution finished ':classes'.
```

### Steps to reproduce the problem

The generated `entities.kt`
```kotlin
package org.example.sqlserver

data class Class (
    val id: Int,
    val classname: String?,
)
```

The generated `entityDefinitions.kt`
```kotlin
package org.example.sqlserver

import org.komapper.annotation.KomapperAutoIncrement
import org.komapper.annotation.KomapperColumn
import org.komapper.annotation.KomapperEntityDef
import org.komapper.annotation.KomapperId
import org.komapper.annotation.KomapperTable

@KomapperEntityDef(Class::class)
@KomapperTable("Class")
data class ClassDef (
    @KomapperId @KomapperColumn("id") val id: Nothing,
    @KomapperColumn("classname") val classname: Nothing,
)
```

The `_ClassDef.kt` generated during compilation:
```kotlin
@file:Suppress("ClassName", "PrivatePropertyName", "UNUSED_PARAMETER", "unused", "RemoveRedundantQualifierName", "MemberVisibilityCanBePrivate", "RedundantNullableReturnType", "USELESS_CAST")
package org.example.sqlserver

// generated at 2022-05-20T16:39:25.390425700+01:00[Europe/London]
@org.komapper.core.dsl.metamodel.EntityMetamodelImplementor(org.example.sqlserver.Class::class)
class _ClassDef private constructor(table: String = "Class", catalog: String = "", schema: String = "", alwaysQuote: Boolean = false, disableSequenceAssignment: Boolean = false, declaration: org.komapper.core.dsl.metamodel.EntityMetamodelDeclaration<_ClassDef> = {}) : org.komapper.core.dsl.metamodel.EntityMetamodel<org.example.sqlserver.Class, kotlin.Int, _ClassDef> {
    private val __tableName = table
    private val __catalogName = catalog
    private val __schemaName = schema
    private val __alwaysQuote = alwaysQuote
    private val __disableSequenceAssignment = disableSequenceAssignment
    private val __declaration = declaration
    private object __EntityDescriptor {
        val id = org.komapper.core.dsl.metamodel.PropertyDescriptor<org.example.sqlserver.Class, kotlin.Int, kotlin.Int>(kotlin.Int::class, kotlin.Int::class, "id", "id", false, false, { it.id }, { e, v -> e.copy(id = v) }, { it }, { it }, false)
        val classname = org.komapper.core.dsl.metamodel.PropertyDescriptor<org.example.sqlserver.Class, kotlin.String, kotlin.String>(kotlin.String::class, kotlin.String::class, "classname", "classname", false, false, { it.classname }, { e, v -> e.copy(classname = v) }, { it }, { it }, true)
    }
    val id: org.komapper.core.dsl.metamodel.PropertyMetamodel<org.example.sqlserver.Class, kotlin.Int, kotlin.Int> by lazy { org.komapper.core.dsl.metamodel.PropertyMetamodelImpl(this, __EntityDescriptor.id) }
    val classname: org.komapper.core.dsl.metamodel.PropertyMetamodel<org.example.sqlserver.Class, kotlin.String, kotlin.String> by lazy { org.komapper.core.dsl.metamodel.PropertyMetamodelImpl(this, __EntityDescriptor.classname) }
    override fun klass() = org.example.sqlserver.Class::class
    override fun tableName() = __tableName
    override fun catalogName() = __catalogName
    override fun schemaName() = __schemaName
    override fun alwaysQuote() = __alwaysQuote
    override fun disableSequenceAssignment() = __disableSequenceAssignment
    override fun declaration() = __declaration
    override fun idGenerator(): org.komapper.core.dsl.metamodel.IdGenerator<org.example.sqlserver.Class, kotlin.Int>? = null
    override fun idProperties(): List<org.komapper.core.dsl.metamodel.PropertyMetamodel<org.example.sqlserver.Class, *, *>> = listOf(id)
    override fun versionProperty(): org.komapper.core.dsl.metamodel.PropertyMetamodel<org.example.sqlserver.Class, *, *>? = null
    override fun createdAtProperty(): org.komapper.core.dsl.metamodel.PropertyMetamodel<org.example.sqlserver.Class, *, *>? = null
    override fun updatedAtProperty(): org.komapper.core.dsl.metamodel.PropertyMetamodel<org.example.sqlserver.Class, *, *>? = null
    override fun properties(): List<org.komapper.core.dsl.metamodel.PropertyMetamodel<org.example.sqlserver.Class, *, *>> = listOf(
        id,
        classname)
    override fun extractId(e: org.example.sqlserver.Class): kotlin.Int = e.id
    override fun convertToId(generatedKey: Long): kotlin.Int? = this.id.wrap(generatedKey.toInt())
    override fun versionAssignment(): Pair<org.komapper.core.dsl.metamodel.PropertyMetamodel<org.example.sqlserver.Class, *, *>, org.komapper.core.dsl.expression.Operand>? = null
    override fun createdAtAssignment(c: java.time.Clock): Pair<org.komapper.core.dsl.metamodel.PropertyMetamodel<org.example.sqlserver.Class, *, *>, org.komapper.core.dsl.expression.Operand>? = null
    override fun updatedAtAssignment(c: java.time.Clock): Pair<org.komapper.core.dsl.metamodel.PropertyMetamodel<org.example.sqlserver.Class, *, *>, org.komapper.core.dsl.expression.Operand>? = null
    override fun preInsert(e: org.example.sqlserver.Class, c: java.time.Clock): org.example.sqlserver.Class = e
    override fun preUpdate(e: org.example.sqlserver.Class, c: java.time.Clock): org.example.sqlserver.Class = e
    override fun postUpdate(e: org.example.sqlserver.Class): org.example.sqlserver.Class = e
    override fun newEntity(m: Map<org.komapper.core.dsl.metamodel.PropertyMetamodel<*, *, *>, Any?>) = org.example.sqlserver.Class(
        id = m[this.id] as kotlin.Int,
        classname = m[this.classname] as kotlin.String?)
    override fun newMetamodel(table: String, catalog: String, schema: String, alwaysQuote: Boolean, disableSequenceAssignment: Boolean, declaration: org.komapper.core.dsl.metamodel.EntityMetamodelDeclaration<_ClassDef>) = _ClassDef(table, catalog, schema, alwaysQuote, disableSequenceAssignment, declaration)
    fun clone(table: String = "Class", catalog: String = "", schema: String = "", alwaysQuote: Boolean = false, disableSequenceAssignment: Boolean = false, declaration: org.komapper.core.dsl.metamodel.EntityMetamodelDeclaration<_ClassDef> = {}) = _ClassDef(table, catalog, schema, alwaysQuote, disableSequenceAssignment, declaration)
    companion object {
        init {
            org.komapper.core.dsl.metamodel.checkMetamodelVersion("org.example.sqlserver._ClassDef", 1)
        }
        val class = _ClassDef()  // Line 51
    }
}

val org.komapper.core.dsl.Meta.class get() = _ClassDef.class  // Line 55
```
Lines 51 and 55 are the problems.

### Versions

- Komapper: 0.33.0
- Kotlin: 1.6.21
- JVM: Corretto
- JDBC Driver or R2DBC Driver: com.microsoft.sqlserver:mssql-jdbc:10.2.0.jre11
- Database: SQL Server
- OS: Windows 10

### Workaround

To get this to compile, you can change the name of the entity class and the corresponding entityDefintion, eg.
```kotlin
package org.example.sqlserver

data class Clazz (
    val id: Int,
    val classname: String?,
)
```

### Suggestion

If the column name collides with a keyword add an underscore to the end of the entity class name, eg.
```kotlin
package org.example.sqlserver

data class Class_ (
    val id: Int,
    val classname: String?,
)
```

**Comment by nakamura-to** [comment]
Thank you for you report.

We have fixed to escape Kotlin keywords.
For example, the identifier `class` is converted to `` `class` ``.
