### ISSUE TITLE
The `kspKotlin` gradle task fails if the entities and entity definitions are in different modules.

### ISSUE THREAD

**Issue by donard-commedagh** [komapper/komapper#622]
### Describe the bug

The `kspKotlin` gradle task fails if the entities and entity definitions are in different modules.

I would like to separate out the Entity data classes into a separate module with no dependency on `komapper` so that I can use them in other apps that don't talk to that database.

When building the module with the Entity definitions in it the `kspKotlin` task fails.

### Expected behavior

The `kspKotlin` task will succeed no matter where the Entity data classes are located

### Actual behavior

Building the project fails with the following output:
```
20:42:21: Executing ':entity-defs:classes :entity-defs:testClasses :entities:classes :entities:testClasses :main:classes :main:testClasses'...

> Task :entities:compileKotlin UP-TO-DATE
> Task :entities:compileJava NO-SOURCE
> Task :entities:processResources NO-SOURCE
> Task :entities:classes UP-TO-DATE
> Task :entities:compileTestKotlin NO-SOURCE
> Task :entities:compileTestJava NO-SOURCE
> Task :entities:processTestResources NO-SOURCE
> Task :entities:testClasses UP-TO-DATE
> Task :main:processResources NO-SOURCE
> Task :main:processTestResources NO-SOURCE

> Task :entity-defs:kspKotlin FAILED
e: [ksp] java.lang.NullPointerException
	at org.komapper.processor.EntityProcessor.generateMetamodel(EntityProcessor.kt:62)
	at org.komapper.processor.EntityProcessor.process(EntityProcessor.kt:36)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension$doAnalysis$4$1.invoke(KotlinSymbolProcessingExtension.kt:220)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension$doAnalysis$4$1.invoke(KotlinSymbolProcessingExtension.kt:218)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension.handleException(KotlinSymbolProcessingExtension.kt:313)
	at com.google.devtools.ksp.AbstractKotlinSymbolProcessingExtension.doAnalysis(KotlinSymbolProcessingExtension.kt:218)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration(TopDownAnalyzerFacadeForJVM.kt:123)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration$default(TopDownAnalyzerFacadeForJVM.kt:99)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:301)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:55)
	at org.jetbrains.kotlin.cli.common.messages.AnalyzerWithCompilerReport.analyzeAndReport(AnalyzerWithCompilerReport.kt:113)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.analyze(KotlinToJVMBytecodeCompiler.kt:292)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:102)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli$default(KotlinToJVMBytecodeCompiler.kt:60)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:172)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:54)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:91)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:43)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:93)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1623)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:359)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:691)
	at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:587)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:828)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:705)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:704)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)

e: Error occurred in KSP, check log for detail

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':entity-defs:kspKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
2 actionable tasks: 1 executed, 1 up-to-date
20:42:23: Execution finished ':entity-defs:classes :entity-defs:testClasses :entities:classes :entities:testClasses :main:classes :main:testClasses'.
```

### Steps to reproduce the problem

I've uploaded a minimal reproducible repository @ https://github.com/donard-commedagh/EntityModuleTest
It doesn't have a JDBC/R2DBC dependency as that doesn't seem to make any difference, it still fails at line 62.
It has three sub-modules:
* `entities` - the data classes representing the Entities
* `entity-defs` - the komapper definition classes for the Entities. [Depends on `:entities`]
* `main` - the application. [Depends on `:entity-defs`]

I've tried running the gradle task with --info and --debug but don't seem to be able to get any extra useful debugging information out of it.

__NOTE__: Given my low skill level with Gradle, I suspect there is something wrong with one of my configurations and would happily be pointed in the right direction.

### Versions

- Komapper: 1.0.0
- Kotlin: 1.6.21
- JVM: OpenJDK 14.0.1
- JDBC Driver or R2DBC Driver: sqlserver-jdbc
- Database: SQL Server
- OS: Windows 10

**Comment by nakamura-to** [comment]
Many thanks for your detailed report and reproducible repository!
We've fixed this issue.
